### ISSUE TITLE
how can i link casperrJS 

### ISSUE THREAD

**Issue by Oyetomi** [C-Rodg/Phantomgram#1]
hello please how can i link caperJs to PhantomJs, ive phantomJs installed on my machine already , and which line tag i meant to edit in the code.

**Comment by Oyetomi** [comment]
var username = 'stfuareyougod',
    password = 'mmmmmm';
var tags = ['sunset', 'seattle'];

var tagUrl = 'https://www.instagram.com/explore/tags/';

// Settings
var casper = require('casper').create({
    logLevel: 'debug',
    waitTimeout: 15000
});
casper.start();
casper.userAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2838.0 Safari/537.36');

// Logging in
casper.thenOpen('https:/instagram.com/accounts/login/', function() {
    this.fill('form', {
        'stfuareyougod' : username,
        'mmmmmm' : password
    }, false);
    this.click('button');
    this.waitFor(function check() {
        return this.evaluate(function() {
            return document.querySelectorAll('article').length > 2;
        });
    }, function then() {
        casper.capture('LoggedIn.png');
    }, function timeout() {
        this.echo("ERROR: Can't get logged in...").exit();
    } );
});

// start navigating to tags
casper.then(function(){
    tags.forEach(function(tag) {
        casper.thenOpen(tagUrl + tag + '/')
        .waitForUrl(tagUrl+tag+'/', function() {
            casper.capture(tag + '.png');
        });
    })
});

casper.run(function() {
    this.echo('ending things');
    this.exit();
});

casper.on('error', function(err) {
    console.log('ERROR EVENT:');
    console.log(err);
});

**Comment by Oyetomi** [comment]
is that a correct input?

**Comment by C-Rodg** [comment]
This project is not yet complete, so all you will currently be able to do is login and load each page. Scraping is not yet supported.  If you are looking for instructions on how to install CasperJs, you can find that [here](http://casperjs.org/).

**Comment by Oyetomi** [comment]
Can I get your personal mail I want you to help me correct a script please

**Comment by C-Rodg** [comment]
That is what this issue forum is for. What is your issue?

**Comment by Oyetomi** [comment]
It's a javascript, I'm trying to run on Phantomjs I don't know why it's not
running

**Comment by C-Rodg** [comment]
Are you running it using the command line? What is your output when you run 'casperjs --version'?

**Comment by Oyetomi** [comment]
its not pertaining to phantogram.

i tried running an instagram like feed bot through phantomJs, but i keep
getting errors and i dont have caperjs installed,

the error i get is

ReferenceError: Can't find variable: $

  undefined:3
  :9
TypeError: null is not an object (evaluating 'point.x')

  phantomjs://code/Photoliker.js:58 in clickElement
  phantomjs://code/Photoliker.js:76
  phantomjs://code/Photoliker.js:167

heres my script ....

var system = require('system');
var username ='thefreelancedude';
var password ='operr24';
var hours ='26';

var page = require('webpage').create();

var stepIndex = 0;
var loadInProgress = false;
var isFinished = true;
var instagramLoginURL = 'https://instagram.com/accounts/login/';

Date.prototype.addHours= function(h){
        this.setHours(this.getHours()+h);
            return this;
}

if (!hours) {
    hours = 24;
} else {
    hours = parseInt(hours);
}

console.log('Username: ' + username);
console.log('Hours to look back: ' + hours);

var targetTime = (new Date()).addHours(-hours);

page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36';
console.log('Current UA: ' + page.settings.userAgent);

page.onConsoleMessage = function (msg, line, source) {
    console.log('console> ' + msg);
};

page.onLoadStarted = function() {
    loadInProgress = true;
};

page.onLoadFinished = function() {
    loadInProgress = false;
};

function next() {
    isFinished = true;
};

function clickElement(selector) {
    var point = page.evaluate(function (selector) {

```
    var el = $(selector)[0];
    var rect = el.getBoundingClientRect();
    return {
        x: rect.left + Math.floor(rect.width / 2),
        y: rect.top + Math.floor(rect.height / 2)
    };
}, selector);
page.sendEvent('click', point.x, point.y);
```

}

function getLatestTime() {
    var timeElements = $('time');
    var length = timeElements.length;
    console.log('Number of visible images: ' + length);
    var dateString = timeElements[length - 1].getAttribute('datetime');
    return new Date(dateString);
};

var steps = [
    function() {
        page.open(instagramLoginURL);
        console.log('Go to: ' + instagramLoginURL);
        next();
    },
    function() {
        clickElement('[name="stfuareyougod"]');
        page.sendEvent('keypress', username);

```
    clickElement('[name="operr24"]');
    page.sendEvent('keypress', password);

    page.render('before-submit.png');
    clickElement('button');

    setTimeout(function () {
        next();
    }, 1000);
},
function() {
    var error = page.evaluate(function () {
        var element = document.getElementById('slfErrorAlert');
        var error_message = false;
        if (element !== null) {
            error_message = element.innerText.trim();
        }
        return error_message;
    });

    page.render('after-submit.png');
    if (!error) {
        console.log('Login Successful: ' + page.url);
    } else {
        console.log('Login Failed: ' + error);
    }
    next();
},
function() {
    var latestTime = page.evaluate(getLatestTime);
    console.log('Target time:' + targetTime);
    console.log('Latest time:' + latestTime);
    if (latestTime <= targetTime) {
        next();
    } else {

        page.evaluate(function() {
            document.body.scrollTop = document.body.scrollHeight;
        });

        clickElement('a:contains("Load more")');
        var scrollInterval = setInterval(function() {

            page.render('after-load-more.png');
            page.evaluate(function() {
                document.body.scrollTop = document.body.scrollHeight;
            });

            var latestTime = page.evaluate(getLatestTime);
            console.log('Latest time:' + latestTime);
            if (latestTime <= targetTime) {
                clearInterval(scrollInterval);
                next();
                return;
            }

        }, 5000);
    }
},
function() {
    var likeButtons = page.evaluate(function() {
        return $('[class~="coreSpriteHeartOpen"]').map(function() {
            return this.getAttribute('data-reactid');
        }).get();
    });
    var length = likeButtons.length;
    console.log('Number of unliked images: ' + length);

    var i = 0;
    var likingInterval = setInterval(function() {
        clickElement('[data-reactid="' + likeButtons[i] + '"]');
        console.log(likeButtons[i]);
        i++;
        if (i >= length) {
            clearInterval(likingInterval);
            next();
        }
    }, 1000);
},
function() {
    page.render('after-liking.png');
    phantom.exit();
}
```

];

setInterval(function() {
    if (isFinished && !loadInProgress && typeof steps[stepIndex] ==
"function") {
        isFinished = false;
        steps[stepIndex]();
        stepIndex++;
    }
}, 50);

**Comment by C-Rodg** [comment]
Seems like you are trying to use a jQuery selector, when you have not included jQuery on the page.

**Comment by Oyetomi** [comment]
How do I fix that please

**Comment by C-Rodg** [comment]
http://phantomjs.org/page-automation.html

**Comment by Oyetomi** [comment]
Am new to javascript

**Comment by Oyetomi** [comment]
If you can please tell me where the error is in the code.
